-- ============================================================================
-- StreaMetrics | Streaming Analytics — Schema DDL
-- Target: SQLite (data/streaming_analytics.db)
--
-- This script is executed via the sqlite3 CLI's dot-commands to import the
-- CSVs generated by python/generate_data.py. Run with:
--   sqlite3 data/streaming_analytics.db < sql/01_schema.sql
-- (Run from the project root so the relative data/*.csv paths resolve.)
-- ============================================================================

PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS watch_events;
DROP TABLE IF EXISTS videos;
DROP TABLE IF EXISTS users;

-- ----------------------------------------------------------------------------
-- users
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    user_id             TEXT PRIMARY KEY,
    signup_date         TEXT NOT NULL,          -- YYYY-MM-DD
    acquisition_channel TEXT NOT NULL,          -- Organic, Creator_Referral, Paid_Social, Search_Ads
    subscription_plan   TEXT NOT NULL           -- Free, Pro, Creator_Tier
);

-- ----------------------------------------------------------------------------
-- videos
-- ----------------------------------------------------------------------------
CREATE TABLE videos (
    video_id            TEXT PRIMARY KEY,
    creator_id          TEXT NOT NULL,
    genre               TEXT NOT NULL,          -- Sci-Fi, AI Animation, AI Shorts, Drama, Horror, Documentaries
    video_duration_sec  INTEGER NOT NULL,
    ai_model_used       TEXT NOT NULL,          -- Kling 2.0, Sora 2, Flux, Seedance Pro
    ai_generated_ratio  REAL NOT NULL,
    monetized           INTEGER NOT NULL        -- 0 or 1
);

-- ----------------------------------------------------------------------------
-- watch_events
-- ----------------------------------------------------------------------------
CREATE TABLE watch_events (
    event_id              TEXT PRIMARY KEY,
    user_id               TEXT NOT NULL,
    video_id              TEXT NOT NULL,
    event_timestamp        TEXT NOT NULL,        -- YYYY-MM-DD HH:MM:SS
    watch_time_sec         INTEGER NOT NULL,
    completion_rate        REAL NOT NULL,
    recreated_by_user      INTEGER NOT NULL,     -- 0 or 1
    liked_by_user          INTEGER NOT NULL,     -- 0 or 1
    shared_by_user         INTEGER NOT NULL,     -- 0 or 1
    ad_revenue_usd          REAL NOT NULL,
    creator_credit_earned  REAL NOT NULL,
    FOREIGN KEY (user_id)  REFERENCES users(user_id),
    FOREIGN KEY (video_id) REFERENCES videos(video_id)
);

-- ----------------------------------------------------------------------------
-- CSV import (sqlite3 CLI dot-commands — must stay in this file for the
-- automated `sqlite3 ... < 01_schema.sql` invocation to load data in one shot)
-- ----------------------------------------------------------------------------
.mode csv

.import --skip 1 data/users.csv users
.import --skip 1 data/videos.csv videos
.import --skip 1 data/watch_events.csv watch_events

-- ----------------------------------------------------------------------------
-- Helpful indexes for analytics workloads
-- ----------------------------------------------------------------------------
CREATE INDEX idx_watch_events_user_id  ON watch_events(user_id);
CREATE INDEX idx_watch_events_video_id ON watch_events(video_id);
CREATE INDEX idx_videos_creator_id     ON videos(creator_id);

-- ----------------------------------------------------------------------------
-- Sanity check row counts
-- ----------------------------------------------------------------------------
SELECT 'users' AS table_name, COUNT(*) AS row_count FROM users
UNION ALL
SELECT 'videos', COUNT(*) FROM videos
UNION ALL
SELECT 'watch_events', COUNT(*) FROM watch_events;
